//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public Empleados()
        {
            this.Permisos = new HashSet<Permisos>();
            this.SalidaEmp = new HashSet<SalidaEmp>();
            this.Licencias = new HashSet<Licencias>();
            this.Vacaciones = new HashSet<Vacaciones>();
        }
    
        public int id { get; set; }
        public string codigoEmp { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int telefono { get; set; }
        public int departamento { get; set; }
        public string cargo { get; set; }
        public string fechaIngreso { get; set; }
        public int salario { get; set; }
        public int estatus { get; set; }
    
        public virtual Cargos Cargos { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        public virtual ICollection<Permisos> Permisos { get; set; }
        public virtual ICollection<SalidaEmp> SalidaEmp { get; set; }
        public virtual ICollection<Licencias> Licencias { get; set; }
        public virtual ICollection<Vacaciones> Vacaciones { get; set; }
    }
}
