//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecursosHEntities : DbContext
    {
        public RecursosHEntities()
            : base("name=RecursosHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cargos> Cargos { get; set; }
        public DbSet<Departamentos> Departamentos { get; set; }
        public DbSet<Empleados> Empleados { get; set; }
        public DbSet<Licencias> Licencias { get; set; }
        public DbSet<Nomina> Nomina { get; set; }
        public DbSet<Permisos> Permisos { get; set; }
        public DbSet<SalidaEmp> SalidaEmp { get; set; }
        public DbSet<Vacaciones> Vacaciones { get; set; }
    }
}
