//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidaEmp
    {
        public int id { get; set; }
        public string codigoEmp { get; set; }
        public string tipoSalida { get; set; }
        public string motivo { get; set; }
        public string fechaSalida { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
